gems:
  - jekyll-feed

name: TODO Group
description: For companies committed to open source.

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      type: "posts"
    values:
      layout: "post"

permalink: /blog/:title/

sass:
  style: :compressed

footer:
    Home: /
    Blog: /blog/
    About: /about/
    Members: /members/
    Join: /join/
    Q&A: /faq/
